name: "Frost Lab"
description: "The New Homepage for the Frost Lab at UCSF"

baseurl: "frostlab.org"

paginate: 5
paginate_path: "blog/page:num"

excerpt_separator: <!--more-->

permalink: pretty
highlighter: pygments
markdown: kramdown
kramdown: 
  parse_block_html: true
